
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdemo?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5